# -*- coding: utf-8 -*-
"""exercise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KfuRfJW3GiHUst9n1tQt_xVXr3Sk27J5
"""

import re
from collections import Counter

def extract_words(text):
    words = re.findall(
        r'\b\w+\b', re.sub(r'\b(?:https?://|www\.)\S+|\b\w+\.(?:org|com|[a-z]{2})\b', '', text.lower())
        )
    word_counts = Counter(words)
    sorted_words = sorted(
        (word for word, count in word_counts.items() if count > 1),
        key=word_counts.get, reverse=True
        )

    return [word for word in sorted_words]